### ISSUE TITLE
No Parachute 1.8

### ISSUE THREAD

**Issue by IAmBattleDashMC** [ItzMace/LastMinerStanding-DEV#139]
When You join the game you don't spawn with any kind of parachute and fall right to your death

### Core information
**Spigot version**: 1.8.9

**LMS version**: 2.0.6

**Plugin list**:  Plugins (49): Bedwars, Languages, VoidWorld, NametagEdit, ViaVersion, StaffPlus, CoreProtect, Skript, CrackShot, SkQuery, BannerBoard, ProtocolLib, LibsDisguises, ChatColorPlus, FastAsyncWorldEdit, PerWorldTabList, WildSkript, PermissionsEx, ConditionalCommands, Vault, HideAndSeek, xInventories, EpicRename, HideAndCustomPlugins, AAC, ASkyBlock, ChestCommands, WatchdogReport, ShopGUIPlus, WorldEdit, Essentials, AACAdditionPro, LiftSign, LiteBans, Citizens, EssentialsChat, SuperVanish, PlotSquared, WorldGuard, HypixelGadgets, CommandNPC, Multiverse-Core, Skellett, LastMinerStanding, HolographicDisplays, TuSKe, SkinsRestorer, skRayFall, Skywars

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.3.0

**ProtocolSupport version**: Don't have this, If I try to get the ProtocolSupport plugin my server crashes right away

**Comment by IAmBattleDashMC** [comment]
Same thing happens when I test it on a local server with only Crackshot, Multiverse, Protocollib, and mls

**Comment by ItzMace** [comment]
Please update to **LastMinerStanding 2.0.7** (latest version) and try it again.

This should have been fixed in Version 2.0.7 already.

Download it here:
https://www.spigotmc.org/resources/lastminerstanding.48445/
