### ISSUE TITLE
Is IT possible to turn protection Off?

### ISSUE THREAD

**Issue by Viinexx1** [ItzMace/LastMinerStanding-DEV#166]
Just a question

**Comment by ItzMace** [comment]
In **config.yml**, you have this part (Gameplay -> Phases -> Ingame -> Warmup):
```
# How long should the players have time to equip before
# PVP will be enabled (in Seconds)
Warmup: 60
```

If you set Warmup to 0, you won't have any protection on game start.

If this did not answer your question, please visit our Discord Server for further support:
[https://discord.gg/J2ca7VD](https://discord.gg/J2ca7VD)

**Comment by Viinexx1** [comment]
I mean Break protection

**Comment by ItzMace** [comment]
The default configuration has in file **config.yml** the following value:
```
# Here you can manage which blocks players should be able to break during ingame:
BlockBreak:
  AllowAll: true
```

This will allow breaking any kind of block.

**Comment by Viinexx1** [comment]
Thank you!
