### ISSUE TITLE
Bandages don't stop bleeding correctly

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#44]
### Issue description

> Bandages don't stop bleeding correctly

### Core information
**Spigot version**: 1.8.8

**LMS version**: 1.1.10

**Plugin list**: LastMinerStanding, ViaVersion

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.3.0

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by SexWexPex** [comment]
Bleeding arent exist.

**Comment by ItzMace** [comment]
This has been fixed in upcoming version 2.0.0.
