### ISSUE TITLE
[AAC] Parachute not working

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#88]
[AAC] Parachute not working, just for OPed players. Non-OPed players don't even get the parachute.

Looks like a false positive due to the rails not being a real object for flight.

**SpigotMC:** v1_8_R3
**AAC:** 3.2.1

**Comment by IAmBattleDashMC** [comment]
Happens even without AAC for me.

**Comment by ItzMace** [comment]
Fixed for AAC 3.5.0-b1
