### ISSUE TITLE
Autoassign existing chests

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#95]
Autoassign existing chests.
Add command to assign existing chests:
`/lms playworld assignchests`

**Suggestions:**
- WorldEdit area: add all chests within a selected area.

@#233146655782731776
```
you should probably add >>
A command like this /lms autoassignsChests or 
( /lms asc name of the chest ) like ( /lms asc guns) this 
command will assigns any chests that is already rendered
 in the world with the chest type guns  ) or you can add a 
( /lms asc guns  swords ) ( priority chests XD ) 50/50 or more type .. )
```

**Comment by TheGameBeastNL** [comment]
Not to the rendered in chunks please, just to the whole world.
Some people like me have a large map to play on :D

**Comment by ItzMace** [comment]
```
/lms playworld findchests <Material>
```
