### ISSUE TITLE
Chest are not filled correctly

### ISSUE THREAD

**Issue by ItzMace** [ItzMace/LastMinerStanding-DEV#96]
@#366954801549934602
```
yes i use  /lms playworld item  =  in the file        Spawn0:
        X: -553
        Y: 69
        Z: 1975 but don't works
```

```
chest  empty
my MC 1.12.2
```

**Comment by Yukyxy** [comment]
I noticed when my players play at Puncher https://www.spigotmc.org/resources/%E2%99%9A-puncher-%E2%99%9A-only-team-minigame-youll-love-limited-price-drop.48784/

 I have this error related to your plugin. https://pastebin.com/KVQ3mqUX

I will try to disable puncher and test your plugin

**Comment by Yukyxy** [comment]
it's same, chest void https://zupimages.net/up/18/11/woqf.png
